# Generated by Django 4.1.1 on 2022-09-10 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventManagment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_event', models.DateTimeField()),
                ('event_complete', models.BooleanField()),
                ('No_of_audience', models.IntegerField()),
            ],
        ),
    ]
