# Generated by Django 4.1.1 on 2022-09-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmanagment',
            name='Email_of_organizer',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
        ),
    ]
